In [ ]:
# 10월_하행 엑셀파일 전부 합치기


import Term_module as Tm
import importlib
importlib.reload(Tm)

folder = '영동선_10월_하행'
save_path = '10월_하행_가공\\10월_하행_통합.xlsx'

intergrated_file = Tm.Intergration(folder)
intergrated_file.read_combine_file()
intergrated_file.save_combined_file(save_path)

,10월,구간,연장,00,01,02,03,04,05,06,...,14,15,16,17,18,19,20,21,22,23
0,1,서창JC ~ 월곶JC,5.8km,82,85,84,82,80,71,68,...,77,78,78,79,80,77,79,82,83,85
1,1,월곶JC ~ 군자JC,3km,85,85,85,82,83,76,73,...,84,85,84,86,87,82,84,87,87,87
2,1,군자JC ~ 군자T/G,2.7km,94,93,94,89,91,87,85,...,93,91,91,92,94,92,93,93,96,95
3,1,군자T/G ~ 서안산IC,1.8km,88,87,88,82,85,82,81,...,84,85,83,84,88,86,87,87,87,89
4,1,서안산IC ~ 안산IC,3.2km,92,90,92,87,89,83,79,...,87,87,87,86,89,89,90,91,92,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,31,호법JC ~ 이천IC,5.7km,93,89,91,90,91,94,90,...,93,92,93,92,91,93,93,93,94,94
740,31,이천IC ~ 여주휴게소,7.2km,96,91,93,92,93,96,95,...,96,97,97,97,95,97,97,97,97,96
741,31,여주휴게소 ~ 여주JC,2.6km,90,89,87,86,88,91,90,...,92,92,91,91,90,90,92,92,92,91
742,31,여주JC ~ 여주IC,4.9km,85,79,83,80,83,76,76,...,95,99,100,96,81,91,80,64,69,78
743,31,여주IC ~ 문막IC,19.9km,93,92,92,90,91,92,94,...,97,100,100,99,97,99,97,95,96,92

In [22]:
# 10월 하행 영동선(서창JC~신갈JC)구간만 포함하기 

import pandas as pd
import Term_module as Tm


file_path = '10월_하행_가공\\10월_하행_통합.xlsx'
save_path = '10월_하행_가공\\10월_하행_가공.xlsx'

Processed_data = Tm.Post_Process(file_path)
Processed_data.delete_row(0,13)
Processed_data.delete_col()
Processed_data.save_processed_file(save_path)

,10월,구간,00,01,02,03,04,05,06,07,...,14,15,16,17,18,19,20,21,22,23
0,1,서창JC ~ 월곶JC,82,85,84,82,80,71,68,69,...,77,78,78,79,80,77,79,82,83,85
1,1,월곶JC ~ 군자JC,85,85,85,82,83,76,73,75,...,84,85,84,86,87,82,84,87,87,87
2,1,군자JC ~ 군자T/G,94,93,94,89,91,87,85,86,...,93,91,91,92,94,92,93,93,96,95
3,1,군자T/G ~ 서안산IC,88,87,88,82,85,82,81,83,...,84,85,83,84,88,86,87,87,87,89
4,1,서안산IC ~ 안산IC,92,90,92,87,89,83,79,83,...,87,87,87,86,89,89,90,91,92,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,31,군포IC ~ 동군포IC,83,82,82,82,82,77,66,28,...,77,75,73,47,30,51,79,82,83,83
729,31,동군포IC ~ 부곡IC,81,80,79,80,80,74,56,37,...,75,71,60,44,38,52,76,78,80,81
730,31,부곡IC ~ 북수원IC,82,81,82,80,80,77,65,65,...,77,75,73,70,66,69,76,77,79,82
731,31,북수원IC ~ 동수원IC,82,82,84,82,81,80,77,78,...,84,83,83,81,76,80,84,81,76,81
732,31,동수원IC ~ 신갈JC,93,92,91,90,91,87,72,44,...,87,85,80,72,65,73,89,89,90,92

In [23]:
# <확인점1> 하행 가장 차 막히는 구간 찾기

import pandas as pd
import Term_module as Tm

file_path = '10월_하행_가공\\10월_하행_가공.xlsx'
save_path = '10월_하행_가공\\10월_날짜별_가장 막힌 구간.xlsx'

Section_data = Tm.Section(file_path)
Section_data.get_avgSpeed()
Section_data.get_day_min_avgspeed_section()
Section_data.save_day_confused_file(save_path)
Section_data.find_most_frequent_section()

'동군포IC ~ 부곡IC'

In [24]:
# <확인점3> 하행 가장 차가 막히는 시간대 찾기

import pandas as pd
import Term_module as Tm 
import importlib
importlib.reload(Tm)

file_path = '10월_하행_가공\\10월_하행_가공.xlsx'
save_path = '10월_하행_가공\\10월_시간대별_평균속도.xlsx'

TimeData = Tm.Time(file_path)
TimeData.get_avgspeed()
TimeData.get_day_min_avgspeed_time()
TimeData.save_confused_time_file(save_path)
TimeData.find_buisiest_time()

'10'

In [25]:
# <명제1> 하행 출근시간대(오전6시~9시) 월요일이 가장 차가 막힐 것이다.

import pandas as pd
import Term_module as Tm 
import importlib
importlib.reload(Tm)

file_path = '10월_하행_가공\\10월_하행_가공.xlsx'
save_path = '10월_하행_가공\\10월_요일별_출근시간.xlsx'

DayData = Tm.Busyday(file_path)
for day_name, day_dates in DayData.day_dates_dict.items():
    DayData.get_day_avgspeed(start=8, end=12, day_dates=day_dates, day_name=day_name)
DayData.combine_day_avgspeed()
DayData.save_confused_GoWork_GoHome_Time(save_path)

          요일       평균속도
0     Monday  52.620192
1    Tuesday  60.026923
2  Wednesday  63.176923
3   Thursday  61.661538
4     Friday  65.379808
5   Saturday  74.610577
6     Sunday  88.379808

In [26]:
# 10월 상행 엑셀파일 전부 합치기
import pandas as pd
import os
import Term_module as Tm

folder = '영동선_10월_상행'
save_path = '10월_상행_가공\\10월_상행_통합.xlsx'

intergrated_file = Tm.Intergration (folder)
intergrated_file.read_combine_file()
intergrated_file.save_combined_file(save_path)

,10월,구간,연장,00,01,02,03,04,05,06,...,14,15,16,17,18,19,20,21,22,23
0,1,문막IC ~ 여주IC,18.2km,99,98,95,93,94,94,96,...,98,97,101,100,99,97,94,94,96,97
1,1,여주IC ~ 여주JC,4.9km,79,78,88,81,77,74,95,...,93,98,100,100,93,77,59,66,77,74
2,1,여주JC ~ 여주휴게소,3.5km,88,88,88,84,83,82,88,...,89,83,90,86,87,83,89,87,91,91
3,1,여주휴게소 ~ 이천IC,6.3km,96,94,93,91,91,90,94,...,93,90,91,93,92,91,93,96,97,97
4,1,이천IC ~ 호법JC,5.7km,95,94,93,92,90,89,92,...,91,89,89,91,90,91,93,95,96,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,31,안산IC ~ 서안산IC,3.2km,84,84,85,83,84,85,82,...,78,71,77,72,77,78,76,87,88,82
740,31,서안산IC ~ 군자T/G,1.8km,92,93,94,89,91,89,85,...,86,84,86,85,85,85,82,89,92,93
741,31,군자T/G ~ 군자JC,2.7km,98,97,98,92,95,94,92,...,91,85,82,91,80,89,89,95,97,99
742,31,군자JC ~ 월곶JC,3km,95,95,93,90,90,90,87,...,78,51,35,60,20,48,70,90,94,96
743,31,월곶JC ~ 서창JC,5.8km,89,88,86,83,83,82,78,...,72,53,53,45,24,37,63,80,85,88

In [27]:
# 10월 상행 영동선(서창JC~신갈JC)구간만 포함하기 

import pandas as pd
import Term_module as Tm

file_path = '10월_상행_가공\\10월_상행_통합.xlsx'
save_path = '10월_상행_가공\\10월_상행_가공.xlsx'

Processed_data = Tm.Post_Process(file_path)
Processed_data.delete_row(11,25)
Processed_data.delete_col()
Processed_data.save_processed_file(save_path)

,10월,구간,00,01,02,03,04,05,06,07,...,14,15,16,17,18,19,20,21,22,23
11,1,신갈JC ~ 동수원IC,89,90,89,88,88,89,88,89,...,87,84,77,83,88,87,88,89,91,93
12,1,동수원IC ~ 북수원IC,85,85,86,85,82,83,82,83,...,77,71,47,67,82,79,80,81,85,88
13,1,북수원IC ~ 부곡IC,88,85,85,85,88,86,82,84,...,81,81,64,51,80,80,77,79,83,85
14,1,부곡IC ~ 동군포IC,84,84,85,84,85,83,79,82,...,76,75,44,39,78,80,79,79,83,84
15,1,동군포IC ~ 군포IC,84,84,84,83,84,83,78,82,...,78,79,74,73,81,81,80,80,82,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,31,안산IC ~ 서안산IC,84,84,85,83,84,85,82,66,...,78,71,77,72,77,78,76,87,88,82
740,31,서안산IC ~ 군자T/G,92,93,94,89,91,89,85,87,...,86,84,86,85,85,85,82,89,92,93
741,31,군자T/G ~ 군자JC,98,97,98,92,95,94,92,93,...,91,85,82,91,80,89,89,95,97,99
742,31,군자JC ~ 월곶JC,95,95,93,90,90,90,87,91,...,78,51,35,60,20,48,70,90,94,96
743,31,월곶JC ~ 서창JC,89,88,86,83,83,82,78,82,...,72,53,53,45,24,37,63,80,85,88

In [28]:
# <확인점2> 상행 가장 차 막히는 구간 찾기

import pandas as pd
import Term_module as Tm

file_path = '10월_상행_가공\\10월_상행_가공.xlsx'
save_path = '10월_상행_가공\\10월_날짜별_가장 막힌 구간.xlsx'

Section_data = Tm.Section(file_path)
Section_data.get_avgSpeed()
Section_data.get_day_min_avgspeed_section()
Section_data.save_day_confused_file(save_path)
Section_data.find_most_frequent_section()

'동수원IC ~ 북수원IC'

In [29]:
# <확인점4> 상행 가장 차가 막히는 시간대 찾기

# 시간대별 평균속도 구하기

import pandas as pd 
import Term_module as Tm

file_path = '10월_상행_가공\\10월_상행_가공.xlsx'
save_path = '10월_상행_가공\\10월_시간대별_평균속도.xlsx'

TimeData = Tm.Time(file_path)
TimeData.get_avgspeed()
TimeData.get_day_min_avgspeed_time()
TimeData.save_confused_time_file(save_path)
TimeData.find_buisiest_time()

'17'

In [30]:
# <명제2> 상행 퇴근시간대(오후4시~7시) 금요일이 가장 차가 막힐 것이다.

# 06~09시에 해당하는 열을 제외한 나머지 시간대 열 삭제

import pandas as pd
import Term_module as Tm

file_path = '10월_상행_가공\\10월_상행_가공.xlsx'
save_path = '10월_상행_가공\\10월_요일별_퇴근시간대.xlsx'

DayData = Tm.Busyday(file_path)
for day_name, day_dates in DayData.day_dates_dict.items():
    DayData.get_day_avgspeed(start=18, end=22, day_dates=day_dates, day_name=day_name)
DayData.combine_day_avgspeed()
DayData.save_confused_GoWork_GoHome_Time(save_path)

          요일       평균속도
0     Monday  60.355769
1    Tuesday  59.953846
2  Wednesday  58.519231
3   Thursday  59.100000
4     Friday  49.937500
5   Saturday  54.889423
6     Sunday  69.100962

In [31]:
# <명제3> 공휴일과 주말은 평일보다 차가 안 막힐 것이다

import pandas as pd 
import Term_module as Tm 
import importlib
importlib.reload(Tm)


file_path = '10월_상행_가공\\10월_상행_가공.xlsx'
save_path = '10월_상행_가공\\10월_평일_공휴일_주말.xlsx'

DayData = Tm.Busyday(file_path)
for day_name, day_dates in DayData.day_dates_dict2.items():
    DayData.get_day_avgspeed(start=2, end=27, day_dates=day_dates, day_name=day_name)
DayData.combine_day_avgspeed()
DayData.save_confused_GoWork_GoHome_Time(save_path)

         요일       평균속도
0   Weekend  79.246795
1   Holiday  83.274573
2  Weekdays  74.498397

In [32]:
# <명제4> 교통량이 많으면 차도 막힐 것이다. 

# 교통량 데이터 가공
import pandas as pd

df = pd.read_excel('영동선_10월_상행_교통량\\교통량.xlsx',header= 1, engine= 'openpyxl')
df1 = df.rename(columns= {'날짜' : '10월'})
df1['10월'] = pd.to_datetime(df1['10월']).dt.day

Traffic = pd.DataFrame()
filtered_df = pd.DataFrame()
for day in range(1, 32):
    section_traffic = df1[df1['10월'] == day ].iloc[:8]
    Traffic = pd.concat([Traffic, section_traffic])
    section_traffic1 = Traffic[Traffic['10월'] == day].iloc[::-1]
    filtered_df = pd.concat([filtered_df, section_traffic1])
    

FinalTraffic = filtered_df.drop(columns= ['차로','방향', '노선명','전일합계(대)'])
FinalTraffic = FinalTraffic.drop(FinalTraffic[(FinalTraffic['구간명'] == '군자TG-월곶JC')].index)
FinalTraffic.to_excel('10월_교통량_가공\\교통량_가공_상행.xlsx', index=False)

FinalTraffic

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,구간명,10월,00~01시,01~02시,02~03시,03~04시,04~05시,05~06시,06~07시,07~08시,...,14~15시,15~16시,16~17시,17~18시,18~19시,19~20시,20~21시,21~22시,22~23시,23~24시
506,신갈JC-동수원IC,1,1138,945,779,671,755,1011,1448,1699,...,4143,4397,4533,4475,3953,3388,3108,2718,2035,1342
505,동수원IC-북수원IC,1,420,361,272,218,297,665,978,1134,...,2421,2710,2913,2506,2020,1786,1777,1559,1018,630
504,부곡IC-동군포IC,1,891,701,662,611,884,1685,2148,2261,...,4009,3957,3928,3742,2905,2759,3247,2896,1773,1117
503,둔대JC-안산JC,1,854,711,665,607,871,1658,2240,2238,...,3912,3897,4006,3776,2885,2670,3069,2919,1710,1105
502,서안산IC-군자TG,1,687,549,469,566,843,1857,2109,1828,...,2778,2766,2888,2568,2021,1633,1813,1755,1098,789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,부곡IC-동군포IC,31,827,738,613,610,911,2123,3733,4216,...,3923,3853,3768,3451,3647,3620,3669,2697,1892,704
4,둔대JC-안산JC,31,822,728,598,614,910,2212,3713,4426,...,4001,4004,3953,3937,3819,3385,3853,2629,1397,1002
3,서안산IC-군자TG,31,691,531,465,499,837,2340,2834,2970,...,2953,3220,2728,3029,2281,2354,2860,1992,1305,963
2,군자TG-군자JC,31,676,517,448,494,797,2269,2816,2955,...,2891,3180,2730,2949,2301,2335,2794,1997,1323,966
0,월곶JC-서창JC,31,776,497,475,459,731,1914,2344,3236,...,3797,4254,4380,3879,3117,3409,3758,2221,1438,1066

In [33]:
# 시간대별 비교
import pandas as pd

df = pd.read_excel('10월_상행_가공\\10월_상행_가공.xlsx')


# 구간 일치시켜주기
df = df.drop(df[df['구간'].isin(['군자JC ~ 월곶JC', '북수원IC ~ 부곡IC', '동군포IC ~ 군포IC', '군포IC ~ 둔대JC', '안산JC ~ 안산IC', '안산IC ~ 서안산IC'])].index)
# 교통량 원본 데이터에 23일과 24일에 대한 데이터가 삭제되어 있어서 똑같이 행을 맞춰줌
df = df.drop(df[df['10월'].isin([23, 24])].index)

df.to_excel('10월_교통량_가공\\평균속도_가공_상행.xlsx', index=False)

# 각 구간마다 교통량이 가장 많은 시간대와 평균속도가 가장 낮은 시간대가 일치하는지 확인

# 상행_ 평균속도
time = df.iloc[:,2:27]
time_means = time.mean().astype(int)

# 가장 평균속도 낮은 시간대 구하기
df_time_means = pd.DataFrame(time_means).reset_index()
df_time_means.columns = ['시간', '평균속도']

Min_AvgSpeed = df_time_means['평균속도'].min()
Busiest_time = df_time_means[df_time_means['평균속도'] == Min_AvgSpeed]['시간'].iloc[0]

# 상행_ 교통량
df_traffic = pd.read_excel('10월_교통량_가공\\교통량_가공_상행.xlsx')

time_traffic = df_traffic.iloc[:, 2:27]

time_traffic = time_traffic.apply(pd.to_numeric, errors='coerce')
time_traffic_means = time_traffic.mean().astype(int)

# 가장 교통량 많은 시간대 구하기
time_traffic_means = pd.DataFrame(time_traffic_means).reset_index()
time_traffic_means.columns = ['시간', '교통량']

Max_AvgTraffic = time_traffic_means['교통량'].max()
Most_Crowded_time = time_traffic_means[time_traffic_means['교통량'] == Max_AvgTraffic]['시간'].iloc[0]

time_traffic_means['시간'] = time_traffic_means['시간'].str.slice(0, 2)
Converged_data = pd.merge(time_traffic_means, df_time_means, on='시간')
Converged_data.to_excel('10월_교통량_가공\\시간별_교통량_속도.xlsx', index=False)

Converged_data

    시간   교통량  평균속도
0   00   814    89
1   01   608    89
2   02   491    88
3   03   504    88
4   04   746    88
5   05  1627    87
6   06  2314    83
7   07  2644    81
8   08  2852    80
9   09  3061    80
10  10  3265    75
11  11  3180    73
12  12  3267    75
13  13  3398    75
14  14  3497    68
15  15  3527    62
16  16  3466    57
17  17  3330    53
18  18  3084    55
19  19  3061    62
20  20  2964    72
21  21  2620    79
22  22  1965    83
23  23  1222    86

In [34]:
# 구간별 비교
import pandas as pd

df = pd.read_excel('10월_상행_가공\\10월_상행_가공.xlsx')

# 구간 일치시켜주기
df = df.drop(df[df['구간'].isin(['군자JC ~ 월곶JC', '북수원IC ~ 부곡IC', '동군포IC ~ 군포IC', '군포IC ~ 둔대JC', '안산JC ~ 안산IC', '안산IC ~ 서안산IC'])].index)
# 교통량 원본 데이터에 23일과 24일에 대한 데이터가 삭제되어 있어서 똑같이 행을 맞춰줌
df = df.drop(df[df['10월'].isin([23, 24])].index)

df.to_excel('10월_교통량_가공\\평균속도_가공_상행.xlsx', index=False)

df['평균속도'] = df.mean(axis=1, numeric_only= True)

# 구간별 평균속도 구하기
section_data = []
valid_days = [day for day in range(1, 32) if day not in [23, 24]]
for day in valid_days:
    day_section = df.loc[df['10월'] == day]
    for section in day_section['구간'].unique():
        section_data.append({
            '구간': section,
            '평균속도': day_section.loc[day_section['구간'] == section, '평균속도'].mean()
        })

original_sections_speed = df['구간'].unique().tolist()  
average_speeds = df.groupby('구간')['평균속도'].mean().astype(int).reset_index()

# 원래 구간 순서대로 정렬
average_speeds['구간'] = pd.Categorical(average_speeds['구간'], categories=original_sections_speed, ordered=True)
average_speeds = average_speeds.sort_values('구간').reset_index(drop=True)

# 구간별 교통량 구하기
df_traffic = pd.read_excel('10월_교통량_가공\\교통량_가공_상행.xlsx')

df_traffic['교통량'] = df_traffic.mean(axis=1, numeric_only= True).astype(int)

section_data = []
valid_days = [day for day in range(1, 32) if day not in [23, 24]]
for day in valid_days:
    day_section = df_traffic.loc[df_traffic['10월'] == day]
    for section in day_section['구간명'].unique():
        section_data.append({
            '구간명': section,
            '교통량': day_section.loc[day_section['구간명'] == section, '교통량'].mean().astype(int)
        })

# 구간별 평균속도 데이터 프레임과 구간별 교통량 데이터 프레임 형식 맞춰주기
df_traffic = df_traffic[~df_traffic['구간명'].str.contains('마성IC-신갈JC')]
original_sections_Traffic = df_traffic['구간명'].unique().tolist()  
average_Traffic = df_traffic.groupby('구간명')['교통량'].mean().astype(int).reset_index()

average_Traffic['구간명'] = pd.Categorical(average_Traffic['구간명'], categories=original_sections_Traffic, ordered=True)
average_Traffic = average_Traffic.sort_values('구간명').reset_index(drop=True)
average_Traffic.rename(columns= {'구간명' : '구간'}, inplace= True)

section_dict = {
    '신갈JC ~ 동수원IC' : '신갈JC-동수원IC',
    '동수원IC ~ 북수원IC' : '동수원IC-북수원IC',
    '부곡IC ~ 동군포IC' : '부곡IC-동군포IC',
    '둔대JC ~ 안산JC' : '둔대JC-안산JC',
    '서안산IC ~ 군자T/G' : '서안산IC-군자TG',
    '군자T/G ~ 군자JC' : '군자TG-군자JC',
    '월곶JC ~ 서창JC' : '월곶JC-서창JC'
}
average_speeds['구간'] = average_speeds['구간'].replace(section_dict)
Converged_data = pd.merge(average_Traffic, average_speeds, on='구간')
Converged_data.to_excel('10월_교통량_가공\\구간별_교통량_속도.xlsx')

Converged_data

C:\Users\손수인\AppData\Local\Temp\ipykernel_18964\358005846.py:66: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  average_speeds['구간'] = average_speeds['구간'].replace(section_dict)

            구간   교통량  평균속도
0   신갈JC-동수원IC  1486    75
1  동수원IC-북수원IC   906    65
2   부곡IC-동군포IC  1547    67
3    둔대JC-안산JC  1527    70
4   서안산IC-군자TG  1104    85
5    군자TG-군자JC  1039    87
6    월곶JC-서창JC  1430    67